version: '1'

name: 'databases'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - 'mysqldb-net'
    volumes:
      - '~/Documents/Databases/mysql:/var/lib/mysql'
  
  adminer:
    image: 'adminer:latest'
    ports:
      - '8084:8080'
    networks:
      - 'mysqldb-net'

networks:
  mysqldb-net:
