version: '1'

name: 'redisdb'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - '${REDIS_FOLDER}:/data'

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - '8087:8081'
    depends_on:
      - redis
