version: '1'

name: 'mongodb'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    networks:
        - 'mongo-compose-net'
    volumes:
      - '${MONGO_FOLDER}:/data/db'

  mongo-express:
    image: 'mongo-express:latest'
    container_name: 'mongo-express'
    ports:
      - '8086:8081'
    networks:
        - 'mongo-compose-net'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  mongo-compose-net:
    driver: bridge
