version: '1'

name: 'postgresdb'
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:14'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - '${POSTGRES_FOLDER}:/var/lib/postgresql/data'
    # restart: always
    
  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '8083:80'
    # restart: always
